### PR TITLE
Enable skipping subsequent actions on payload outcome

### LINKED ISSUE #8: Sherlock workflow fails when no JS code block is present
I just opened an issue over at https://github.com/yarnpkg/berry/issues/2517 and got a bunch of emails telling me "Run failed: Sherlock for Yarn". Looking at the actual run, the error appears to be because "no JS code block got found". https://github.com/yarnpkg/berry/runs/1976830896?check_suite_focus=true#step:5:172. I assume this workflow should simply be a no-op when no JS test case is present in the issue instead of failing a bunch?

image

### PR DESCRIPTION
**Pull request by sargunv**
Resolves #8.

I see you were using the neutral exit code 78, which is no longer supported in GH Actions v2. This PR adds a new output value on the payload step that's then used as a condition to skip the subsequent steps. It also updates the readme with an example of how the new output is meant to be consumed.

If accepted and released, I'll PR https://github.com/yarnpkg/berry/ to use these changes, so folks opening issues on that repo won't get a bunch of "workflow failed" emails.

Note that `continue-on-error: true` in the workflow will also hide other failures, like the `throw new UsageError()` at the top of `payload.ts`. If we don't want to do that, the payload command should be amended to return exit code 0 instead of 78 so we can remove `continue-on-error`. I didn't include that in this PR because it'd be a breaking change (Sherlock users would now be required to check the new output in their workflow), but if you'd prefer that approach then I can switch to that.

Tested locally like this:

image

### CODE REVIEW

**Comment by arcanis** [comment]
Thanks for looking into that! I've tried integrating it, but it doesn't seem to work:
https://github.com/yarnpkg/berry/runs/2003449778?check_suite_focus=true

However I properly added the `if` properties:
https://github.com/yarnpkg/berry/blob/master/.github/workflows/sherlock-workflow.yml#L29

Any idea what I might be missing?

**Comment by arcanis** [comment]
For some reason the step output seems to be `success` ... no idea why 😕
https://github.com/yarnpkg/berry/runs/2003525804?check_suite_focus=true#step:6:2

**Comment by arcanis** [comment]
Found the problem! The right variable wasn't `steps.sherlock-payload.outcome`, but rather `steps.sherlock-payload.outputs.outcome`. Subtle!

**Comment by sargunv** [comment]
Oh my bad, glad you figured it out!

**Pull request merged**
